[package]
name = "pakket"
version = "0.1.0"
edition = "2021"

[dependencies]
directories = "4.0.1"

[dependencies.clap]
version = "4.1.4"
default-features = false
features = ["std", "help", "usage", "suggestions", "derive"]
